name: medium
description: Medium scraper
version: 0.0.1
homepage: https://github.com/PlugFox/medium
repository: https://github.com/PlugFox/medium
issue_tracker: https://github.com/PlugFox/medium/issues

environment:
  sdk: '>=2.18.3 <3.0.0'

dependencies:
  meta: ^1.7.0
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  puppeteer: ^2.15.0
  path: any
  l: ^3.2.0
  drift: ^2.2.0
  multiline: ^3.0.0
  html: ^0.15.1
  http: ^0.13.5
  sqlite3: any

dev_dependencies:
  test: ^1.15.0
  coverage: any
  drift_dev: ^2.2.0
  build_runner: ^2.3.2
